services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotcc
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`x0ryz.cc`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_public"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true